Repository microsoft/ebpf-for-windows, pull requests merged in 2022-11, with the labels that each got.

#1467 Fuzz test netebpfext helper(s)
  .github/workflows/cicd.yml
  Directory.Build.props
  ebpfapi/ebpfapi.vcxproj
  ebpfapi/rpc_client.cpp
  ebpfsvc/rpc_util.cpp
  include/user/ebpf_registry_helper.h
  libs/api_common/api_common.cpp
  libs/api_common/windows_helpers.cpp
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_native.h
  libs/execution_context/ebpf_program.c
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/execution_context/user/execution_context_user.vcxproj
  libs/platform/CMakeLists.txt
  libs/platform/ebpf_extension.c
  libs/platform/ebpf_platform.h
  libs/platform/kernel/platform_kernel.vcxproj
  libs/platform/kernel/platform_kernel.vcxproj.filters
  libs/platform/unit/platform_unit_test.cpp
  libs/platform/user/ebpf_extension_user.c
  libs/platform/user/framework.h
  libs/platform/user/kernel_um.cpp
  libs/platform/user/kernel_um.h
  libs/platform/user/nmr_impl.cpp
  libs/platform/user/nmr_impl.h
  libs/platform/user/nmr_um.cpp
  libs/platform/user/platform_user.vcxproj
  libs/platform/user/platform_user.vcxproj.filters
  libs/service/service.vcxproj
  libs/ubpf/user/ubpf_user.c
  libs/ubpf/user/ubpf_user.vcxproj
  netebpfext/user/ndis_um.cpp
  netebpfext/user/netebpfext_user.vcxproj
  netebpfext/user/netebpfext_user.vcxproj.filters
  scripts/create_execution_context_corpus.bat
  tests/api_test/CMakeLists.txt
  tests/end_to_end/helpers.h
  tests/end_to_end/netsh_test.cpp
  tests/fuzz/CMakeLists.txt
  tests/fuzz/execution_context.cpp
  tests/libfuzzer/core_helper_fuzzer/core_helper_fuzzer.vcxproj
  tests/libfuzzer/core_helper_fuzzer/core_helper_fuzzer.vcxproj.filters
  tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj.filters
  tests/libfuzzer/execution_context/libfuzz_harness.cpp
  tests/libs/util/CMakeLists.txt
  tests/libs/util/catch_wrapper.hpp
  tests/netebpfext_unit/netebpf_ext_helper.h
  tests/performance/CMakeLists.txt
  tests/sample/ext/app/CMakeLists.txt
  tests/unit/CMakeLists.txt
Labels: enhancement

#1512 Emulate driver verifier systematic low memory mode
  .github/workflows/cicd.yml
  .github/workflows/reusable-test.yml
  libs/platform/CMakeLists.txt
  libs/platform/user/ebpf_low_memory_test.cpp
  libs/platform/user/ebpf_low_memory_test.h
  libs/platform/user/ebpf_platform_user.cpp
  libs/platform/user/platform_user.vcxproj
  libs/platform/user/platform_user.vcxproj.filters
  scripts/Test-LowMemory.ps1
  scripts/setup_build/setup_build.vcxproj
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/test_helper.cpp
  tests/end_to_end/test_helper.hpp
  tests/libs/common/passed_test_log.h
  tests/libs/util/wer_report.hpp
  tests/unit/test.vcxproj
Labels: tests

#1600 Resolve nmr_binding_handle to only in external calls
  libs/platform/user/nmr_impl.cpp
  libs/platform/user/nmr_impl.h
Labels: bug

#1578 Add brief details about and link to, windbg's .kdfiles command (#1493)
  docs/GettingStarted.md
Labels: documentation

#1597 Add notes re. over-rides to LLVM coding style (#1546)
  docs/DevelopmentGuide.md
Labels: documentation

#1564 Annotate platform API's with _Must_inspect_result_
  libs/api/ebpf_api.cpp
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_async.c
  libs/platform/ebpf_async.h
  libs/platform/ebpf_epoch.c
  libs/platform/ebpf_epoch.h
  libs/platform/ebpf_etw.c
  libs/platform/ebpf_extension.c
  libs/platform/ebpf_handle.h
  libs/platform/ebpf_hash_table.c
  libs/platform/ebpf_object.c
  libs/platform/ebpf_object.h
  libs/platform/ebpf_pinning_table.c
  libs/platform/ebpf_pinning_table.h
  libs/platform/ebpf_platform.h
  libs/platform/ebpf_ring_buffer.c
  libs/platform/ebpf_ring_buffer.h
  libs/platform/ebpf_serialize.c
  libs/platform/ebpf_serialize.h
  libs/platform/ebpf_state.c
  libs/platform/ebpf_state.h
  libs/platform/ebpf_trampoline.c
  libs/platform/kernel/ebpf_handle_kernel.c
  libs/platform/kernel/ebpf_native_kernel.c
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/kernel/framework.h
  libs/platform/unit/platform_unit_test.cpp
  libs/platform/user/ebpf_handle_user.c
  libs/platform/user/ebpf_native_user.c
  libs/platform/user/ebpf_platform_user.cpp
  libs/platform/user/framework.h
  tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp
  tests/libfuzzer/execution_context/libfuzz_harness.cpp
  tests/performance/ExecutionContext.cpp
  tests/performance/performance.cpp
  tests/performance/platform.cpp
Labels: cleanup

#1608 Check for detached client before firing
  tests/end_to_end/helpers.h
Labels: bug, tests, low-memory

#1606 Check for NULL return from ebpf_enumerate_sections and ebpf_api_elf_disassemble_section
  libs/ebpfnetsh/elf.cpp
Labels: bug, low-memory

#1612 Rundown fd on _test_helper_end_to_end terminate
  tests/end_to_end/test_helper.cpp
Labels: bug, tests

#1619 Fix double free of program fd in handle_ebpf_add_program()
  libs/ebpfnetsh/programs.cpp
Labels: bug

#1623 Close handle via fd to prevent orphaned fd
  libs/api/ebpf_api.cpp
Labels: bug

#1616 bpf_object__open should fail if it hits low memory failure
  libs/api/ebpf_api.cpp
Labels: bug

#1568 Annotate execution context API's with _Must_inspect_result_
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_core.h
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_link.h
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_maps.h
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_native.h
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_program.h
  libs/execution_context/unit/execution_context_unit_test.cpp
  tests/fuzz/execution_context.cpp
  tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp
  tests/libfuzzer/execution_context/libfuzz_harness.cpp
  tests/performance/ExecutionContext.cpp
Labels: cleanup

#1569 Annotate EBPF API's with _Must_inspect_result_
  include/ebpf_api.h
  libs/api/Verifier.cpp
  libs/api/Verifier.h
  libs/api/api_internal.h
  libs/api/ebpf_api.cpp
  libs/api/rpc_client.h
  libs/api_common/api_common.cpp
  libs/api_common/api_common.hpp
  libs/api_common/device_helper.cpp
  libs/api_common/device_helper.hpp
  libs/api_common/store_helper_internal.cpp
  libs/api_common/store_helper_internal.h
  libs/api_common/windows_platform_common.cpp
  libs/api_common/windows_platform_common.hpp
  libs/service/api_service.cpp
  tests/bpftool_tests/bpftool_tests.cpp
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/helpers.h
  tests/end_to_end/test_helper.cpp
  tools/port_quota/port_quota.cpp
Labels: cleanup

#1592 Fix maximum entry tracking for hash map type maps.
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_native.c
  libs/platform/ebpf_async.c
  libs/platform/ebpf_epoch.c
  libs/platform/ebpf_hash_table.c
  libs/platform/ebpf_pinning_table.c
  libs/platform/ebpf_platform.h
  libs/platform/ebpf_state.c
  libs/platform/unit/platform_unit_test.cpp
  tests/performance/platform.cpp
Labels: bug

#1643 Assert on deadlock in shutting down
  libs/platform/user/nmr_impl.cpp
Labels: tests

#1594 Fix code scanning alert - Comparison of narrow type with wide type in…
  libs/api_common/windows_platform_common.cpp
  libs/platform/user/ebpf_platform_user.cpp
  libs/service/api_service.cpp
  tests/sample/ext/app/sample_ext_app.cpp
Labels: cleanup

#1570 Annotate remaining code with _Must_inspect_result_
  ebpfapi/rpc_client.cpp
  include/kernel/ebpf_registry_helper.h
  include/user/ebpf_registry_helper.h
  libs/api_common/registry_helper.cpp
  libs/api_common/store_helper_internal.cpp
  libs/ebpfnetsh/programs.cpp
  libs/ebpfnetsh/utilities.cpp
  libs/ebpfnetsh/utilities.h
  libs/service/api_service.cpp
  libs/service/api_service.h
  libs/service/verifier_service.cpp
  libs/service/verifier_service.h
  libs/thunk/mock/mock.cpp
  netebpfext/net_ebpf_ext.c
  netebpfext/net_ebpf_ext.h
  netebpfext/net_ebpf_ext_bind.c
  netebpfext/net_ebpf_ext_hook_provider.c
  netebpfext/net_ebpf_ext_hook_provider.h
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/helpers.h
  tests/end_to_end/test_helper.cpp
  tests/end_to_end/test_helper.hpp
  tests/netebpfext_unit/netebpfext_unit.cpp
  tests/sample/ext/drv/sample_ext.c
  tests/sample/ext/drv/sample_ext.h
  tests/sample/ext/drv/sample_ext_drv.c
Labels: cleanup

#1620 Instrument all allocation paths
  libs/api/Verifier.cpp
  libs/api/ebpf_api.cpp
  libs/api/libbpf_link.cpp
  libs/api/libbpf_program.cpp
  libs/api_common/api_common.cpp
  libs/ebpfnetsh/programs.cpp
  libs/platform/unit/platform_unit_test.cpp
  libs/platform/user/ebpf_low_memory_test.cpp
  libs/platform/user/ebpf_platform_user.cpp
  libs/platform/user/kernel_um.cpp
Labels: cleanup

#1665 Add table of supported eBPF instructions
  docs/NativeCodeGeneration.md
  docs/isa-support.rst
  scripts/.check-license.ignore
Labels: documentation

#1676 Update doc to include step to install VC redist package.
  docs/InstallEbpf.md
Labels: documentation

#1547 Return module handle on native module load
  ebpfcore/ebpf_drv.c
  libs/api/api_internal.h
  libs/api/ebpf_api.cpp
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_native.h
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_protocol.h
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_handle.h
  libs/platform/ebpf_object.c
  libs/platform/ebpf_object.h
  libs/platform/ebpf_platform.h
  libs/platform/kernel/ebpf_handle_kernel.c
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/unit/platform_unit_test.cpp
  libs/platform/user/ebpf_handle_user.c
  libs/platform/user/ebpf_platform_user.cpp
  tests/api_test/CMakeLists.txt
  tests/api_test/api_test.cpp
  tests/api_test/api_test.vcxproj
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/test_helper.cpp
  tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp
  tests/libs/util/ioctl_helper.cpp
  tests/libs/util/ioctl_helper.h
Labels: bug
