Repository microsoft/ebpf-for-windows, pull requests merged in 2022-06, with the labels that each got.

#1183 Update hash in GettingStarted.md
  docs/GettingStarted.md
Labels: bug, documentation

#1164 Add bpf2c fuzzer and execution context fuzzer to CI/CD
  .github/workflows/cicd.yml
  .github/workflows/reusable-test.yml
  Directory.Build.props
  ebpf-for-windows.sln
  ebpfapi/ebpfapi.vcxproj
  libs/platform/user/ebpf_platform_user.cpp
  scripts/create_bpf2c_corpus.bat
  tests/libfuzzer/bpf2c/bpf2c_fuzzer.vcxproj
  tests/libfuzzer/bpf2c/bpf2c_fuzzer.vcxproj.filters
  tests/libfuzzer/execution_context/corpus.zip
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj.filters
  tests/libfuzzer/execution_context/libfuzz_harness.cpp
  tools/bpf2c/bpf2c.vcxproj
  tools/bpf2c/bpf_code_generator.cpp
Labels: security, tests

#1153 Add fuzzer for core helper functions
  .github/workflows/cicd.yml
  ebpf-for-windows.sln
  libs/execution_context/ebpf_maps.c
  scripts/create_core_helper_corpus.bat
  tests/libfuzzer/README.md
  tests/libfuzzer/core_helper_fuzzer/core_helper_fuzzer.vcxproj
  tests/libfuzzer/core_helper_fuzzer/core_helper_fuzzer.vcxproj.filters
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_csum_diff
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_get_current_pid_tgid
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_get_prandom_u32
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_get_smp_processor_id
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_ktime_get_boot_ns
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_ktime_get_ns
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_map_delete_elem
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_map_lookup_and_delete_elem
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_map_lookup_elem
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_map_peek_elem
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_map_pop_elem
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_map_push_elem
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_map_update_elem
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_ringbuf_output
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_tail_call
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_trace_printk2
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_trace_printk3
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_trace_printk4
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_trace_printk5
  tests/libfuzzer/core_helper_fuzzer/corpus/bpf_xdp_adjust_head
  tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp
Labels: security, tests

#1163 Enable verifier fuzzer in github CI/CD
  .github/workflows/cicd.yml
  scripts/create_verifier_corpus.bat
  tests/libfuzzer/verifier/verifier_fuzzer.vcxproj
  tests/libfuzzer/verifier/verifier_fuzzer.vcxproj.filters
Labels: security, tests

#1173 Change default program type to EBPF_PROGRAM_TYPE_UNSPECIFIED
  include/ebpf_api.h
  include/ebpf_structs.h
  libs/api/Verifier.cpp
  libs/api/ebpf_api.cpp
  libs/api/libbpf_program.cpp
  libs/api_common/CMakeLists.txt
  libs/api_common/api_common.cpp
  libs/api_common/api_common.hpp
  libs/api_common/api_common.vcxproj
  libs/api_common/api_common.vcxproj.filters
  libs/api_common/utilities.cpp
  libs/api_common/utilities.hpp
  libs/api_common/windows_platform_common.cpp
  libs/api_common/windows_program_type.h
  libs/ebpfnetsh/elf.cpp
  libs/service/api_service.cpp
  libs/service/verifier_service.cpp
  tests/bpf2c_tests/expected/bpf_dll.c
  tests/bpf2c_tests/expected/bpf_raw.c
  tests/bpf2c_tests/expected/bpf_sys.c
  tests/bpf2c_tests/expected/cgroup_sock_addr_dll.c
  tests/bpf2c_tests/expected/cgroup_sock_addr_raw.c
  tests/bpf2c_tests/expected/cgroup_sock_addr_sys.c
  tests/cilium/cilium_tests.cpp
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/netsh_test.cpp
  tests/end_to_end/test_helper.cpp
  tests/libfuzzer/verifier/libfuzz_harness.cpp
  tests/unit/libbpf_test.cpp
  tools/bpf2c/bpf2c.cpp
  tools/encode_program_info/encode_program_info.cpp
Labels: enhancement

#1214 Mark unsafe strings via unsafe_string class
  ebpf-for-windows.sln
  tests/bpf2c_tests/raw_bpf.cpp
  tools/bpf2c/bpf2c.cpp
  tools/bpf2c/bpf_code_generator.cpp
  tools/bpf2c/bpf_code_generator.h
Labels: bug

#1215 Api test fixes
  libs/api/libbpf_program.cpp
  tests/api_test/api_test.cpp
Labels: tests

#1224 Fix LPM crash with malformed key
  libs/execution_context/ebpf_maps.c
Labels: bug

#1226 _update_lpm_map_entry should reject call with NULL key
  libs/execution_context/ebpf_maps.c
  libs/execution_context/unit/execution_context_unit_test.cpp
Labels: bug

#1199 Gather dumps on STATUS_STACK_BUFFER_OVERRUN exception
  tests/libs/util/wer_report.hpp
Labels: tests

#1213 fix test failure incorrectly treated as success
  .github/workflows/cicd.yml
  .github/workflows/reusable-test.yml
Labels: tests
