Repository microsoft/ebpf-for-windows, pull requests merged in 2022-08, with the labels that each got.

#1310 Add negative tests for native module
  libs/execution_context/ebpf_native.c
  libs/platform/user/ebpf_platform_user.cpp
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/test_helper.cpp
  tests/sample/unsafe/invalid_maps3.c
Labels: tests

#1305 Add noexcept keyword to various internal APIs
  include/ebpf_api.h
  libs/api/Verifier.cpp
  libs/api/api_internal.h
  libs/api/ebpf_api.cpp
  libs/api_common/windows_platform_common.cpp
  tests/end_to_end/helpers.h
Labels: cleanup

#1327 Add note about WDK vsix checkbox when installing WDK
  docs/GettingStarted.md
Labels: documentation

#1361 Fix invalid map value size for prog_array and map_array
  libs/execution_context/ebpf_maps.c
  libs/execution_context/unit/execution_context_unit_test.cpp
Labels: bug

#1368 Clean up the deprecated netsh use of bpf_object__for_each_safe()
  libs/ebpfnetsh/programs.cpp
Labels: cleanup

#1377 Remove trailing whitespace in committed files
  CONTRIBUTING.md
  docs/InstallEbpf.md
  images/install-ebpf-for-windows.ps1
  tests/unit/CMakeLists.txt
  tools/bpf2c/CMakeLists.txt
Labels: cleanup

#1383 Fix leak of reference on WDFREQUEST
  ebpfcore/ebpf_drv.c
Labels: bug
