Repository microsoft/ebpf-for-windows, pull requests merged in 2022-12, with the labels that each got.

#1687 enable loading of native programs with no maps
  libs/api/ebpf_api.cpp
  tests/api_test/api_test.cpp
Labels: bug

#1627 Re-enable low memory test
  .github/workflows/cicd.yml
Labels: tests

#1737 Cleanup
  include/ebpf_utilities.h
  libs/api/api_internal.h
  libs/api/ebpf_api.cpp
  libs/api_common/store_helper_internal.cpp
  libs/api_common/windows_platform_common.cpp
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_link.h
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_maps.h
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/platform/ebpf_hash_table.c
  libs/platform/ebpf_interlocked.c
  libs/platform/ebpf_pinning_table.c
  libs/platform/ebpf_platform.h
  libs/platform/ebpf_serialize.c
  libs/platform/ebpf_state.c
  libs/platform/ebpf_trampoline.c
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/user/ebpf_platform_user.cpp
Labels: cleanup

#1724 Speed up build of sample folder
  tests/sample/sample.vcxproj
  tools/bpf2c/Convert-BpfToNative.ps1.template
Labels: optimization

#1742 platform library are missing SAL annotation
  libs/platform/ebpf_handle.h
  libs/platform/kernel/ebpf_handle_kernel.c
  libs/platform/user/ebpf_handle_user.c
Labels: cleanup

#1726 Implement multi-generational LRU
  libs/execution_context/ebpf_maps.c
  tests/performance/ExecutionContext.cpp
Labels: optimization

#1752 Rolling lru test and fix for heap corruption
  libs/execution_context/ebpf_maps.c
  libs/platform/ebpf_hash_table.c
  libs/platform/ebpf_platform.h
  tests/performance/ExecutionContext.cpp
Labels: bug

#1770 Add support for logging leaked allocations
  .github/workflows/cicd.yml
  .github/workflows/reusable-test.yml
  libs/platform/CMakeLists.txt
  libs/platform/user/ebpf_leak_detector.cpp
  libs/platform/user/ebpf_leak_detector.h
  libs/platform/user/ebpf_low_memory_test.cpp
  libs/platform/user/ebpf_platform_user.cpp
  libs/platform/user/ebpf_symbol_decoder.h
  libs/platform/user/platform_user.vcxproj
  libs/platform/user/platform_user.vcxproj.filters
Labels: tests

#1774 First round of memory leak fixes in ebpfapi
  libs/api_common/store_helper_internal.cpp
  libs/api_common/windows_platform_common.cpp
  libs/ebpfnetsh/elf.cpp
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/unit/platform_unit_test.cpp
  libs/platform/user/ebpf_platform_user.cpp
  libs/platform/user/kernel_um.cpp
  libs/platform/user/platform_user.vcxproj.filters
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/helpers.h
  tests/end_to_end/test_helper.cpp
Labels: bug
