Repository microsoft/ebpf-for-windows, pull requests merged in 2022-09, with the labels that each got.

#1372 Update nuget package to include export_program_info.exe
  tools/nuget/ebpf-for-windows.nuspec
Labels: bug

#1386 Add nuget docs
  docs/GettingStarted.md
Labels: documentation

#1396 Add workaround for netsh regression
  tools/netsh/dllmain.c
Labels: bug

#1407 Fix docs on show verification
  docs/tutorial.md
  tools/netsh/ebpfnetsh.rc
Labels: documentation

#1421 Fix get_attach_type_windows()
  libs/api_common/windows_platform_common.cpp
Labels: bug

#1414 Use installer instead of building from source in the Tutorial
  docs/tutorial.md
Labels: documentation

#1411 Implement correct division by zero behavior
  tests/bpf2c_tests/expected/divide_by_zero_dll.c
  tests/bpf2c_tests/expected/divide_by_zero_raw.c
  tests/bpf2c_tests/expected/divide_by_zero_sys.c
  tests/bpf2c_tests/raw_bpf.cpp
  tests/end_to_end/end_to_end.cpp
  tools/bpf2c/bpf_code_generator.cpp
  tools/bpf2c/bpf_code_generator.h
Labels: bug, security

#1423 Fix the bpf_map_lookup_elem / bpf_map_update_elem API for per-cpu maps.
  include/ebpf_structs.h
  libs/api/ebpf_api.cpp
  libs/api/libbpf_system.cpp
  libs/execution_context/ebpf_maps.c
  libs/platform/ebpf_platform.h
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/user/ebpf_platform_user.cpp
  tests/unit/libbpf_test.cpp
Labels: bug
