Repository microsoft/ebpf-for-windows, pull requests merged in 2022-10, with the labels that each got.

#1446 Clean up msi and ci/cd
  .github/workflows/reusable-build.yml
  docs/InstallEbpf.md
  scripts/config_test_vm.psm1
  scripts/create_package_data.bat
Labels: cleanup

#1445 Clean up unused code in header files
  include/ebpf_api.h
  tests/end_to_end/helpers.h
Labels: cleanup

#1485 Add bpf2c test logs to test artifacts
  .github/workflows/reusable-test.yml
Labels: github_actions

#1499 Fix VS2019 requesting to retarget projects.
  ebpfapi/ebpfapi.vcxproj
  libs/execution_context/user/execution_context_user.vcxproj
  libs/ubpf/user/ubpf_user.vcxproj
Labels: bug

#1477 Remove reference to broken link
  docs/DevelopmentGuide.md
Labels: bug, documentation

#1482 Fix script to use provide VM name
  scripts/deploy-ebpf.ps1.in
Labels: bug

#1475 Add bpf2c_plugin for use with bpf_conformance test suite
  .github/workflows/cicd.yml
  .github/workflows/reusable-build.yml
  .github/workflows/reusable-test.yml
  docs/InstallEbpf.md
  docs/tutorial.md
  ebpf-for-windows.sln
  include/bpf2c.h
  tests/CMakeLists.txt
  tests/bpf2c_plugin/CMakeLists.txt
  tests/bpf2c_plugin/bpf2c_plugin.cpp
  tests/bpf2c_plugin/bpf2c_plugin.vcxproj
  tests/bpf2c_plugin/bpf2c_plugin.vcxproj.filters
  tests/bpf2c_plugin/bpf2c_test.cpp
Labels: enhancement

#1504 Startup failures under low memory
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/platform/ebpf_async.c
  libs/platform/ebpf_epoch.c
  libs/platform/ebpf_pinning_table.c
  libs/platform/ebpf_state.c
  libs/platform/kernel/ebpf_extension_kernel.c
Labels: bug
