Repository microsoft/ebpf-for-windows, pull requests merged in 2022-07, with the labels that each got.

#1260 Fix automation script
  scripts/config_test_vm.psm1
Labels: bug

#1257 Add program type option for "netsh ebpf show verification" commands
  libs/ebpfnetsh/elf.cpp
  tests/end_to_end/netsh_test.cpp
  tools/netsh/ebpfnetsh.rc
Labels: enhancement

#1261 Remove export_program_info dependencies
  libs/api_common/CMakeLists.txt
  libs/service/CMakeLists.txt
  libs/service/service.vcxproj
  tests/unit/CMakeLists.txt
Labels: cleanup

#1268 Fix test automation
  scripts/config_test_vm.psm1
  scripts/run_driver_tests.psm1
Labels: bug, tests

#1267 Fix store read logic.
  include/ebpf_store_helper.h
  include/ebpf_windows.h
  libs/api_common/store_helper_internal.cpp
Labels: bug

#1286 Fix ring buffer test subscriber logic.
  libs/api/ebpf_api.cpp
  libs/platform/ebpf_platform.h
  libs/platform/ebpf_ring_buffer.c
  tests/libs/common/common_tests.cpp
Labels: bug

#1292 Explain where to find the wprp file
  docs/GettingStarted.md
Labels: documentation

#1296 Clean up Verifier.cpp
  include/ebpf_api.h
  libs/api/Verifier.cpp
  tests/end_to_end/end_to_end.cpp
Labels: cleanup

#1302 Clean up ebpf_program.c
  libs/execution_context/ebpf_program.c
Labels: cleanup
