Repository microsoft/ebpf-for-windows, pull requests merged in 2023-05, with the labels that each got.

#2379 Add netsh command to enumerate processes using eBPF
  .github/workflows/cicd.yml
  libs/ebpfnetsh/CMakeLists.txt
  libs/ebpfnetsh/ebpfnetsh.vcxproj
  libs/ebpfnetsh/ebpfnetsh.vcxproj.filters
  libs/ebpfnetsh/pins.cpp
  libs/ebpfnetsh/processes.cpp
  libs/ebpfnetsh/processes.h
  libs/ebpfnetsh/programs.cpp
  resource/ebpf_resource.rc
  tests/end_to_end/netsh_test.cpp
  tests/end_to_end/netsh_test_helper.h
  tools/netsh/dllmain.c
  tools/netsh/ebpfnetsh.rc
  tools/netsh/resource.h
Labels: enhancement

#2393 ensure native ebpf program's helper function count is non-zero before using it for allocation computations.
  docs/AutomatedTests.md
  installer/Product.wxs
  libs/execution_context/ebpf_program.c
  scripts/deploy-ebpf.ps1.in
  tests/bpf2c_tests/expected/cgroup_mt_connect4_dll.c
  tests/bpf2c_tests/expected/cgroup_mt_connect4_raw.c
  tests/bpf2c_tests/expected/cgroup_mt_connect4_sys.c
  tests/bpf2c_tests/expected/cgroup_mt_connect6_dll.c
  tests/bpf2c_tests/expected/cgroup_mt_connect6_raw.c
  tests/bpf2c_tests/expected/cgroup_mt_connect6_sys.c
  tests/sample/cgroup_mt_connect4.c
  tests/sample/cgroup_mt_connect6.c
  tests/stress/km/stress_tests_km.cpp
Labels: bug

#2407 Add kernel tests for native_only build.
  .github/workflows/cicd.yml
  scripts/vm_run_tests.psm1
  tests/api_test/api_test.cpp
  tests/bpftool_tests/bpftool_tests.cpp
  tests/connect_redirect/connect_redirect_tests.cpp
  tests/libs/util/CMakeLists.txt
  tests/libs/util/native_helper.cpp
  tests/libs/util/native_helper.hpp
  tests/libs/util/test_util.vcxproj
  tests/libs/util/test_util.vcxproj.filters
  tests/sample/ext/app/sample_ext_app.cpp
  tests/socket/socket_tests.cpp
Labels: tests

#2420 Wait for preemptible work items to complete in UM mock.
  libs/execution_context/ebpf_native.c
  libs/platform/user/ebpf_platform_user.cpp
  tests/end_to_end/test_helper.cpp
Labels: bug, tests

#2452 propertly initialize pe_section_name_counter
  tools/bpf2c/bpf_code_generator.h
Labels: bug

#2448 Disable JIT (and interpret) from "regular-native_only" CI/CD build
  Directory.Build.props
Labels: bug

#2459 _ebpf_object_tracking_list_insert returns success if table is full
  libs/platform/ebpf_object.c
Labels: bug

#2458 Remove premature assert
  libs/execution_context/ebpf_link.c
Labels: bug

#2467 KM Multi-threaded stress tests - Code clean-up, duplicate code refactoring
  tests/stress/ebpf_mt_stress.h
  tests/stress/ebpf_stress_tests.cpp
  tests/stress/km/stress_tests_km.cpp
  tests/stress/readme.md
  tests/stress/um/stress_tests_um.cpp
Labels: bug

#2344 Add check for IRQL between epoch enter / exit
  libs/platform/ebpf_epoch.c
Labels: enhancement

#2472 Revert bpf_printk thunk
  tests/bpf2c_tests/expected/map_dll.c
  tests/bpf2c_tests/expected/map_raw.c
  tests/bpf2c_tests/expected/map_sys.c
  tests/sample/map.c
Labels: bug

#2450 Load/Attach/Unload programs only once for connect_redirect tests.
  scripts/vm_run_tests.psm1
  tests/connect_redirect/connect_redirect_tests.cpp
  tests/end_to_end/end_to_end.cpp
  tests/libs/common/common_tests.h
  tests/stress/km/stress_tests_km.cpp
  tests/stress/um/stress_tests_um.cpp
Labels: bug, tests

#2479 Access "program->links" under lock
  libs/execution_context/ebpf_program.c
Labels: bug

#2483 Fix build errors with Visual Studio 17.6.0
  Directory.Build.props
  libs/platform/user/platform_user.vcxproj
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj
Labels: bug

#2484 Capture bpftool output in diagnostic scripts
  scripts/ebpf_tracing.cmd
  scripts/ebpf_tracing_periodic_task.xml
Labels: enhancement

#2455 Configuring Segment Heap for bpf2c binary
  tools/bpf2c/bpf2c.exe.manifest.in
  tools/bpf2c/bpf2c.vcxproj
  tools/bpf2c/bpf2c.vcxproj.filters
Labels: bug

#2515 Remove double free of ebpf_map_t
  libs/api/ebpf_api.cpp
Labels: bug

#2514 Don't throw exceptions from ~_single_instance_hook
  tests/end_to_end/helpers.h
Labels: bug, tests

#2500 Fix closing native program / maps handles in system worker thread.
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/platform/ebpf_platform.h
  libs/platform/kernel/ebpf_handle_kernel.c
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/user/ebpf_platform_user.cpp
  tests/api_test/api_test.cpp
Labels: bug

#2519 kernel mode stress test - tweak extension stop/restart, better handling of test runtime
  tests/stress/km/stress_tests_km.cpp
Labels: bug, tests

#2532 Fix sock_addr tracing bug
  netebpfext/net_ebpf_ext_sock_addr.c
Labels: bug

#2499 Tune ebpf_tracing.cmd to use the least amount of CPU.
  scripts/ebpf_tracing.cmd
  scripts/ebpf_tracing_periodic_task.xml
Labels: optimization

#2501 Refactor eBPFCore tracing to use less stack space.
  ebpfapi/ebpfapi.vcxproj
  ebpfapi/ebpfapi.vcxproj.filters
  ebpfapi/rpc_client.cpp
  ebpfcore/ebpf_drv.c
  ebpfsvc/eBPFSvc.vcxproj
  ebpfsvc/eBPFSvc.vcxproj.filters
  libs/api/api.vcxproj
  libs/api/api.vcxproj.filters
  libs/api/ebpf_api.cpp
  libs/api/libbpf_map.cpp
  libs/api_common/device_helper.hpp
  libs/api_common/windows_platform_common.cpp
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/platform/CMakeLists.txt
  libs/platform/ebpf_async.c
  libs/platform/ebpf_epoch.c
  libs/platform/ebpf_etw.c
  libs/platform/ebpf_object.c
  libs/platform/ebpf_pinning_table.c
  libs/platform/ebpf_platform.h
  libs/platform/ebpf_ring_buffer.c
  libs/platform/ebpf_serialize.c
  libs/platform/ebpf_state.c
  libs/platform/ebpf_tracelog.c
  libs/platform/ebpf_tracelog.h
  libs/platform/ebpf_trampoline.c
  libs/platform/kernel/ebpf_handle_kernel.c
  libs/platform/kernel/ebpf_native_kernel.c
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/kernel/platform_kernel.vcxproj
  libs/platform/kernel/platform_kernel.vcxproj.filters
  libs/platform/user/ebpf_handle_user.c
  libs/platform/user/ebpf_platform_user.cpp
  libs/platform/user/platform_user.vcxproj
  libs/platform/user/platform_user.vcxproj.filters
  netebpfext/net_ebpf_ext_tracelog.h
  tests/libfuzzer/core_helper_fuzzer/core_helper_fuzzer.vcxproj
  tests/libfuzzer/core_helper_fuzzer/core_helper_fuzzer.vcxproj.filters
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj.filters
  tests/libfuzzer/verifier_fuzzer/verifier_fuzzer.vcxproj
  tests/libfuzzer/verifier_fuzzer/verifier_fuzzer.vcxproj.filters
  tests/netebpfext_unit/netebpfext_unit.vcxproj
  tests/netebpfext_unit/netebpfext_unit.vcxproj.filters
  tests/stress/km/ebpf_stress_tests_km.vcxproj
  tests/stress/um/ebpf_stress_tests_um.vcxproj
  tests/unit/test.vcxproj
  tests/unit/test.vcxproj.filters
  tools/export_program_info/export_program_info.vcxproj
  tools/export_program_info/export_program_info.vcxproj.filters
Labels: optimization
