Repository microsoft/ebpf-for-windows, pull requests merged in 2023-04, with the labels that each got.

#2257 Ensure refcounts for extension provider data access
  libs/execution_context/ebpf_program.c
Labels: bug

#2267 Fix memory leaks
  libs/ebpfnetsh/programs.cpp
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/test_helper.cpp
Labels: bug

#2250 Check program state before permitting linking
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_program.h
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_object.c
  libs/platform/ebpf_object.h
  libs/platform/ebpf_platform.h
  netebpfext/net_ebpf_ext_sock_addr.c
Labels: bug

#2289 connect_redirect tests: Add check that source port is not 0
  tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c
  tests/connect_redirect/connect_redirect_tests.cpp
  tests/sample/cgroup_sock_addr2.c
  tests/socket/socket_tests_common.h
Labels: tests

#2322 Cleanup netebpfext_unit tests for fault injection
  libs/platform/user/ebpf_fault_injection.cpp
  scripts/Test-FaultInjection.ps1
  tests/netebpfext_unit/netebpfext_unit.cpp
Labels: tests

#2319 Handle map concurrency in `test_helper`.
  tests/end_to_end/test_helper.cpp
Labels: bug, tests

#2327 Check for crash dumps on workflow faiure
  .github/workflows/reusable-test.yml
  tests/libs/common/ebpf_watchdog_timer.h
  tests/libs/common/watchdog.h
  tests/unit/wer_report_test_wrapper.cpp
Labels: enhancement, tests

#2317 Fix memory leak when async_ioctl call fails.
  libs/api/ebpf_api.cpp
  libs/api_common/device_helper.hpp
  libs/platform/ebpf_platform.h
Labels: bug

#2329 Fix ebpf_program_batch_end_invoke_function_t definition and clean up NPI
  docs/eBpfExtensions.md
  include/ebpf_extension.h
  libs/execution_context/ebpf_link.c
  netebpfext/net_ebpf_ext_hook_provider.c
  netebpfext/net_ebpf_ext_hook_provider.h
  tests/sample/ext/drv/sample_ext.c
  tests/sample/ext/drv/sample_ext.h
Labels: bug

#2324 Deregister for helper function change when deleting native module
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_program.h
Labels: bug

#2313 Protect link->client_data.data with lock
  libs/execution_context/ebpf_link.c
Labels: bug

#2345 Set WFP sublayer weight to maximum
  netebpfext/net_ebpf_ext.c
Labels: enhancement

#2321 Add compartment support to netsh ebpf add program
  libs/ebpfnetsh/programs.cpp
  libs/ebpfnetsh/tokens.h
  tests/end_to_end/netsh_test.cpp
  tools/netsh/ebpfnetsh.rc
Labels: enhancement

#2355 Fix use after free in native code.
  libs/execution_context/ebpf_native.c
Labels: bug

#2356 NativeCodeGeneration.md: Doc update with hash information
  docs/NativeCodeGeneration.md
Labels: documentation

#2359 Add fault injection in ndis_um.cpp
  netebpfext/net_ebpf_ext_xdp.c
  netebpfext/user/ndis_um.cpp
Labels: bug

#2361 Update release steps.
  docs/ReleaseProcess.md
Labels: documentation

#2347 Merge create and initialize to limit data races
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_link.h
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_program.h
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_object.h
  tests/performance/ExecutionContext.cpp
Labels: bug

#2352 Capture crash dumps during build phase and upload them
  .github/workflows/reusable-build.yml
Labels: enhancement, ci/cd

#2340 Prevent object ref-count from transitioning from 0 to 1
  ebpf-for-windows.sln
  libs/platform/ebpf_interlocked.c
  libs/platform/ebpf_object.c
  libs/platform/ebpf_platform.h
Labels: cleanup

#2343 netebpfext tracing changes
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/net_ebpf_ext_tracelog.h
Labels: enhancement

#2357 Add eBPF & WFP tracing script.
  scripts/ebpf_tracing.cmd
Labels: enhancement

#2383 Update scorecard workflow to latest
  .github/workflows/scorecards-analysis.yml
Labels: bug, ci/cd

#2382 Prefer HKCU over HKLM for ebpf store
  libs/api_common/store_helper_internal.cpp
Labels: bug

#2374 Fix code coverage upload count in .github/codecov.yml.
  .github/codecov.yml
Labels: bug, ci/cd

#2396 Harden link state machine
  libs/execution_context/ebpf_link.c
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_extension.c
Labels: bug

#2391 Get Build-x64-FuzzerDebug build output even on failure
  .github/workflows/reusable-build.yml
Labels: enhancement, ci/cd

#2226 socket tests and redirection tests does not clean up bpf_object on failure
  tests/connect_redirect/connect_redirect_tests.cpp
  tests/end_to_end/end_to_end.cpp
  tests/libs/common/common_tests.h
  tests/socket/socket_tests.cpp
Labels: bug, tests

#2380 Add Fault Injection in WFP OS APIs
  netebpfext/net_ebpf_ext.c
  netebpfext/user/fwp_um.cpp
Labels: bug

#2395 Close native object handles in a work item in case of failure
  libs/api/ebpf_api.cpp
  libs/execution_context/ebpf_native.c
Labels: bug

#2400 Added parameters to `ebpf_tracing.cmd`, revised tracing/cleanup logic
  scripts/ebpf_tracing.cmd
  scripts/ebpf_tracing_periodic_task.xml
  scripts/ebpf_tracing_startup_task.xml
Labels: enhancement
