Repository microsoft/ebpf-for-windows, pull requests merged in 2023-09, with the labels that each got.

#2820 Fix build artifact circular dependency
  .github/workflows/reusable-build.yml
Labels: bug, ci/cd

#2865 Update Release documentation.
  docs/ReleaseProcess.md
Labels: documentation

#2851 Connect Redirect Test fixes
  tests/connect_redirect/connect_redirect_tests.cpp
  tests/libs/util/socket_helper.cpp
  tests/libs/util/socket_helper.h
  tests/tcp_udp_listener/tcp_udp_listener.cpp
Labels: tests

#2869 Fix double-free in api_common
  libs/api_common/windows_platform_common.cpp
Labels: bug

#2849 Remove check that prevents fuzzing below minimum size
  Directory.Build.props
  ebpfcore/ebpf_drv.c
  libs/api/libbpf_program.cpp
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_program.c
  libs/runtime/ebpf_epoch.c
  libs/shared/tracelog.c
  netebpfext/net_ebpf_ext_bind.c
  netebpfext/net_ebpf_ext_tracelog.c
  netebpfext/sys/net_ebpf_ext_drv.c
  tests/libfuzzer/core_helper_fuzzer/libfuzz_harness.cpp
  tests/libfuzzer/execution_context/libfuzz_harness.cpp
  tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp
  tests/sample/ext/drv/sample_ext_drv.c
  tools/bpf2c/bpf2c.cpp
  tools/bpf2c/bpf_code_generator.cpp
Labels: enhancement, tests

#2850 Add WS 2022 self-hosted runners.
  .github/workflows/cicd.yml
  .github/workflows/reusable-test.yml
  docs/SelfHostedRunnerSetup.md
  scripts/test_execution.json
Labels: enhancement, tests, ci/cd

#2906 Update isa-support.rst
  docs/isa-support.rst
Labels: bug, documentation

#2918 Fix netsh show maps alignment issue
  libs/ebpfnetsh/maps.cpp
  tests/end_to_end/netsh_test.cpp
Labels: bug
