Repository microsoft/ebpf-for-windows, pull requests merged in 2023-11, with the labels that each got.

#3078 Update release process.
  .github/workflows/cicd-release-validation.yml
  docs/ReleaseProcess.md
Labels: ci/cd

#3069 Update isa-support table
  docs/isa-support.rst
Labels: documentation

#3058 Zero initialize batch context state
  docs/eBpfExtensions.md
  include/ebpf_extension.h
  libs/execution_context/ebpf_link.c
Labels: bug
