Repository microsoft/ebpf-for-windows, pull requests merged in 2023-03, with the labels that each got.

#2114 Wrap registry APIs behind store APIs.
  include/ebpf_store_helper.h
  include/kernel/ebpf_registry_helper.h
  libs/api_common/store_helper_internal.cpp
  libs/api_common/store_helper_internal.h
  libs/api_common/windows_platform_common.cpp
  libs/platform/kernel/ebpf_platform_kernel.c
  netebpfext/net_ebpf_ext_bind.c
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/net_ebpf_ext_sock_ops.c
  netebpfext/net_ebpf_ext_xdp.c
  tests/netebpfext_unit/netebpf_ext_helper.cpp
  tests/sample/ext/drv/sample_ext.c
  tools/export_program_info/CMakeLists.txt
  tools/export_program_info/export_program_info.cpp
  tools/export_program_info/export_program_info.vcxproj
  tools/export_program_info/export_program_info.vcxproj.filters
  tools/export_program_info/main.cpp
Labels: enhancement, cleanup

#2170 Enable low memory simulation for netebpfext unit tests.
  .github/workflows/cicd.yml
  netebpfext/net_ebpf_ext.c
  netebpfext/net_ebpf_ext_bind.c
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/net_ebpf_ext_sock_ops.c
  netebpfext/net_ebpf_ext_xdp.c
  tests/netebpfext_unit/netebpfext_unit.cpp
Labels: bug, tests

#2192 Enable leak_detection for "fault_injection" test case.
  .github/workflows/cicd.yml
  libs/api/Verifier.cpp
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/unit/platform_unit_test.cpp
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/helpers.h
Labels: bug, tests

#2190 Fix memory leaks in netebpfext
  .github/workflows/cicd.yml
  libs/platform/user/kernel_um.h
  netebpfext/net_ebpf_ext_bind.c
  netebpfext/net_ebpf_ext_hook_provider.c
  netebpfext/net_ebpf_ext_sock_ops.c
Labels: bug, tests

#2253 Simulate NMR API failures: Fix memory leaks and segmentation fault
  libs/api/ebpf_api.cpp
  libs/api_common/store_helper_internal.cpp
  libs/execution_context/ebpf_native.c
Labels: bug
