Repository microsoft/ebpf-for-windows, pull requests merged in 2023-02, with the labels that each got.

#1929 enable app verifier for cicd build
  .github/workflows/cicd.yml
Labels: enhancement, tests

#1995 Add support for deploying eBPF to arbitrary filesystem locations
  docs/InstallEbpf.md
  scripts/deploy-ebpf.ps1.in
Labels: enhancement

#1988 Document epoch based memory management
  docs/EpochBasedMemoryManagement.md
Labels: documentation

#2000 Catch and terminate exception in ebpf_ring_buffer_map_subscribe
  libs/api/ebpf_api.cpp
Labels: bug

#2005 Delay NMR registration until link is ready
  libs/api_common/api_common.hpp
  libs/execution_context/ebpf_link.c
Labels: bug

#1999 Catch std::bad_alloc from ParsePEFromFile
  libs/api/ebpf_api.cpp
Labels: bug

#2003 perform a default action if the XDP program fails
  netebpfext/net_ebpf_ext_xdp.c
Labels: bug

#2027 Incorporate post-merge feedback
  include/ebpf_result.h
  libs/execution_context/ebpf_maps.c
  libs/platform/ebpf_object.c
Labels: cleanup

#1706 Add full low-memory-test
  .github/workflows/cicd.yml
Labels: enhancement, tests

#2009 Invoke _ebpf_extension_client_notify_change before completing binding
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_program.c
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_extension.c
  libs/platform/ebpf_platform.h
Labels: bug

#2042 Update connect redirect tests to test only-v4 and only-v6 program scenarios.
  scripts/run_driver_tests.psm1
  tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c
  tests/connect_redirect/connect_redirect_tests.cpp
  tests/sample/cgroup_sock_addr2.c
Labels: bug, tests

#2040 Add Wix Toolset as a `nuget` package.
  .github/workflows/reusable-build.yml
  docs/GettingStarted.md
  installer/ebpf-for-windows.wixproj
  installer/packages.config
Labels: enhancement

#2029 Add test case for XDP_TX
  netebpfext/user/fwp_um.cpp
  netebpfext/user/ndis.h
  netebpfext/user/ndis_um.cpp
  tests/netebpfext_unit/netebpfext_unit.cpp
Labels: enhancement, tests

#2047 Fix bullet formatting in docs.
  docs/GettingStarted.md
Labels: documentation

#2049 Workaround to avoid race between attach failing and unregister
  docs/GettingStarted.md
  libs/platform/user/nmr_impl.cpp
  libs/platform/user/nmr_impl.h
Labels: bug

#1936 Add support for atomic instructions in bpf2c
  docs/isa-support.rst
  include/bpf2c.h
  tests/bpf2c_tests/elf_bpf.cpp
  tests/bpf2c_tests/expected/atomic_instruction_fetch_add_dll.c
  tests/bpf2c_tests/expected/atomic_instruction_fetch_add_raw.c
  tests/bpf2c_tests/expected/atomic_instruction_fetch_add_sys.c
  tests/bpf2c_tests/expected/atomic_instruction_others_dll.c
  tests/bpf2c_tests/expected/atomic_instruction_others_raw.c
  tests/bpf2c_tests/expected/atomic_instruction_others_sys.c
  tests/sample/atomic_instruction_fetch_add.c
  tests/sample/atomic_instruction_others.o
  tests/sample/sample.vcxproj
  tools/bpf2c/bpf_code_generator.cpp
  tools/bpf2c/templates/user_mode_bpf2c.vcxproj
Labels: enhancement

#2011 Don't enable hook extension rundown until NMR binding is complete
  libs/platform/user/kernel_um.cpp
  libs/platform/user/kernel_um.h
  netebpfext/net_ebpf_ext_hook_provider.c
Labels: bug

#2062 Add option to invoke eBPF programs in batch mode
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_program.h
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_extension.c
  libs/platform/ebpf_platform.h
  libs/platform/ebpf_state.c
  libs/platform/ebpf_state.h
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/unit/platform_unit_test.cpp
  libs/platform/user/ebpf_platform_user.cpp
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/helpers.h
  tests/netebpfext_unit/netebpf_ext_helper.cpp
  tests/performance/ExecutionContext.cpp
  tests/unit/libbpf_test.cpp
Labels: optimization

#1909 Add multiple pool tags for ebpfcore
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_link.c
  libs/execution_context/ebpf_maps.c
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/platform/ebpf_epoch.c
  libs/platform/ebpf_epoch.h
  libs/platform/ebpf_platform.h
  libs/platform/ebpf_ring_buffer.c
  libs/platform/ebpf_state.c
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/user/ebpf_platform_user.cpp
Labels: enhancement

#2013 XDP: complete TX clones upon injection failure
  netebpfext/net_ebpf_ext_xdp.c
Labels: bug

#2102 Fix local_service_name leak in ebpf_native_load
  libs/execution_context/ebpf_native.c
Labels: bug

#2084 Fix native module unit tests for low memory simulation scenario
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/test_helper.cpp
  tests/end_to_end/test_helper.hpp
Labels: bug, tests

#2098 SAL annotation for several source codes
  libs/ebpfnetsh/elf.cpp
  libs/ebpfnetsh/links.cpp
  libs/ebpfnetsh/maps.cpp
  libs/ebpfnetsh/pins.cpp
Labels: cleanup

#2110 Add merge_queue support in CI/CD
  .github/workflows/cicd.yml
  .github/workflows/scorecards-analysis.yml
Labels: optimization, ci/cd

#2115 Enable scorecards to run in merge queue
  .github/workflows/reusable-test.yml
  .github/workflows/scorecards-analysis.yml
Labels: bug, ci/cd

#2113 Connect-Redirect test setup - Delete standard user account before its recreation.
  scripts/vm_run_tests.psm1
Labels: bug

#2060 Query and delete connection context atomically
  netebpfext/net_ebpf_ext_sock_addr.c
Labels: bug

#2117 Remove autoupdate workflow
  .github/workflows/autoupdate.yaml
Labels: cleanup

#2094 Fix regression on msbuild Release builds.
  tests/sample/sample.vcxproj
  tests/sample/unsafe/atomic_instruction_others.o
Labels: bug

#2067 Handle re-auth case.
  netebpfext/net_ebpf_ext.h
  netebpfext/net_ebpf_ext_sock_addr.c
Labels: bug

#2103 Protect object lists in ebpfapi with mutex
  libs/api/api_internal.h
  libs/api/ebpf_api.cpp
  libs/execution_context/ebpf_native.c
  libs/platform/ebpf_epoch.c
  libs/platform/ebpf_object.c
  libs/platform/ebpf_pinning_table.c
  libs/platform/user/ebpf_handle_user.c
  tests/unit/libbpf_test.cpp
Labels: bug

#2120 Skip scorecard steps in merge queue
  .github/workflows/scorecards-analysis.yml
Labels: bug, ci/cd

#2091 Export new sock_addr specific helper function (windows only)
  docs/SelfHostedRunnerSetup.md
  docs/eBpfExtensions.md
  include/ebpf_nethooks.h
  libs/execution_context/ebpf_program.c
  netebpfext/net_ebpf_ext_bind.c
  netebpfext/net_ebpf_ext_prog_info_provider.c
  netebpfext/net_ebpf_ext_prog_info_provider.h
  netebpfext/net_ebpf_ext_program_info.h
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/net_ebpf_ext_sock_ops.c
  netebpfext/net_ebpf_ext_xdp.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c
  tests/netebpfext_unit/netebpf_ext_helper.cpp
  tests/sample/cgroup_sock_addr2.c
  tests/sample/ext/drv/sample_ext.c
  tests/sample/ext/drv/sample_ext_drv.c
  tests/sample/ext/inc/sample_ext_helpers.h
Labels: enhancement

#2124 Add netebpfext user mode tests
  .github/workflows/cicd.yml
  libs/platform/user/ebpf_platform_user.cpp
  netebpfext/net_ebpf_ext_hook_provider.c
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/user/fwp_um.cpp
  netebpfext/user/fwp_um.h
  tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp
  tests/netebpfext_unit/netebpf_ext_helper.cpp
  tests/netebpfext_unit/netebpf_ext_helper.h
  tests/netebpfext_unit/netebpfext_unit.cpp
Labels: bug, tests

#2143 Set github workflow egress-policy to block
  .github/workflows/reusable-test.yml
  .github/workflows/scorecards-analysis.yml
  .github/workflows/update-docs.yml
Labels: enhancement, security, ci/cd
