Repository microsoft/ebpf-for-windows, pull requests merged in 2023-01, with the labels that each got.

#1799 Free link-object returned from bpf_program__attach_xdp
  tests/unit/libbpf_test.cpp
Labels: bug

#1812 Fix memory leak in bpf_prog_attach
  libs/api/libbpf_program.cpp
Labels: bug

#1811 Update docs to indicate j*32 ebpf instruction support in bpf2c
  docs/isa-support.rst
Labels: documentation

#1825 Add bpf_prog_test_run_opts support
  docs/Fuzzing.md
  docs/eBpfExtensions.md
  ebpfapi/Source.def
  include/ebpf_api.h
  include/ebpf_program_types.h
  include/ebpf_result.h
  include/linux/bpf.h
  libs/api/bpf_syscall.cpp
  libs/api/ebpf_api.cpp
  libs/api/libbpf_program.cpp
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_program.h
  libs/execution_context/ebpf_protocol.h
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_platform.h
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/user/ebpf_platform_user.cpp
  tests/end_to_end/helpers.h
  tests/unit/libbpf_test.cpp
Labels: enhancement

#1827 Support for extension to get the program context
  docs/eBpfExtensions.md
  libs/execution_context/ebpf_program.c
  netebpfext/net_ebpf_ext_bind.c
  netebpfext/net_ebpf_ext_prog_info_provider.c
  netebpfext/net_ebpf_ext_prog_info_provider.h
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/net_ebpf_ext_sock_ops.c
  netebpfext/net_ebpf_ext_xdp.c
  tests/netebpfext_unit/netebpf_ext_helper.cpp
  tests/sample/ext/drv/sample_ext.c
  tests/sample/ext/drv/sample_ext_drv.c
  tests/sample/ext/inc/sample_ext_helpers.h
Labels: enhancement

#1860 Add test for bpftool prog run
  tests/bpftool_tests/bpftool_tests.cpp
Labels: enhancement

#1865 Prune inactive threads from the epoch thread table
  libs/platform/ebpf_epoch.c
Labels: enhancement, cleanup

#1870 Fix netebpfext fuzzer bug with prog types other than xdp
  netebpfext/user/fwp_um.cpp
  netebpfext/user/fwp_um.h
  tests/libfuzzer/netebpfext_fuzzer/corpus/bind
  tests/libfuzzer/netebpfext_fuzzer/corpus/cgroup_sock_addr
  tests/libfuzzer/netebpfext_fuzzer/corpus/sock_ops
  tests/libfuzzer/netebpfext_fuzzer/corpus/xdp
  tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp
  tests/netebpfext_unit/netebpf_ext_helper.h
Labels: bug, tests

#1866 Implementation of syscalls in bpf_syscall.cpp
  include/linux/bpf.h
  libs/api/bpf_syscall.cpp
  tests/unit/libbpf_test.cpp
Labels: enhancement

#1906 Fix race condition in ebpf_link_detach_program() and _ebpf_link_instance_invoke()
  libs/execution_context/ebpf_link.c
Labels: bug

#1876 Remove dependency on trampoline table for interpret and native.
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_native.c
  libs/execution_context/ebpf_program.c
  libs/execution_context/ebpf_program.h
  libs/execution_context/unit/execution_context_unit_test.cpp
  libs/platform/ebpf_extension.c
  netebpfext/net_ebpf_ext.c
  netebpfext/sys/net_ebpf_ext_drv.c
Labels: bug

#1913 Add doc about automated tests
  CONTRIBUTING.md
  docs/AutomatedTests.md
Labels: documentation

#1895 Add unit tests for BIND, CGROUP_SOCK_ADDR, and SOCK_OPS
  include/ebpf_nethooks.h
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/user/fwp_um.cpp
  netebpfext/user/fwp_um.h
  tests/libfuzzer/netebpfext_fuzzer/libfuzz_harness.cpp
  tests/netebpfext_unit/netebpf_ext_helper.cpp
  tests/netebpfext_unit/netebpf_ext_helper.h
  tests/netebpfext_unit/netebpfext_unit.cpp
Labels: enhancement, tests

#1899 Add helper functions to bpf_endian.h
  include/bpf_endian.h
Labels: enhancement

#1914 Shave 8+ minutes off the overall build time
  .github/workflows/cicd.yml
Labels: tests

#1920 Remove the obsolete fuzz.exe
  .github/workflows/cicd.yml
  docs/Fuzzing.md
  ebpf-for-windows.sln
  tests/CMakeLists.txt
  tests/fuzz/CMakeLists.txt
  tests/fuzz/execution_context.cpp
  tests/fuzz/fuzz.vcxproj
  tests/fuzz/fuzz.vcxproj.filters
Labels: cleanup

#1919 List test executables in testing document
  docs/AutomatedTests.md
  docs/Governance.md
Labels: documentation

#1932 Fix leak in __bpf_set_link_xdp_fd_replace()
  libs/api/libbpf_program.cpp
  libs/platform/user/ebpf_leak_detector.cpp
Labels: bug

#1945 Ensure core, api initialization for netsh unit tests
  tests/end_to_end/netsh_test.cpp
Labels: bug, tests

#1935 Normalize fuzzer & coverage library reference inconsistencies.
  Directory.Build.props
  ebpf-for-windows.sln
  ebpfapi/ebpfapi.vcxproj
  tests/libfuzzer/bpf2c_fuzzer/bpf2c_fuzzer.vcxproj
  tests/libfuzzer/bpf2c_fuzzer/bpf2c_fuzzer.vcxproj.filters
  tests/libfuzzer/bpf2c_fuzzer/libfuzz_harness.cpp
  tests/libfuzzer/core_helper_fuzzer/core_helper_fuzzer.vcxproj
  tests/libfuzzer/execution_context/execution_context_fuzzer.vcxproj
  tests/libfuzzer/netebpfext_fuzzer/netebpfext_fuzzer.vcxproj
  tests/libfuzzer/verifier_fuzzer/libfuzz_harness.cpp
  tests/libfuzzer/verifier_fuzzer/verifier_fuzzer.vcxproj
  tests/libfuzzer/verifier_fuzzer/verifier_fuzzer.vcxproj.filters
  tools/bpf2c/bpf2c.vcxproj
Labels: cleanup

#1942 fix to `ring_buffer__new` API
  libs/api/libbpf_map.cpp
Labels: bug

#1944 Remove dependabot tracking for nuget packages
  .github/dependabot.yml
Labels: cleanup, ci/cd

#1950 Skip CI/CD build and tests for doc-only changes
  .github/workflows/cicd.yml
  .github/workflows/reusable-build.yml
  .github/workflows/reusable-test.yml
  .github/workflows/scorecards-analysis.yml
Labels: optimization, ci/cd

#1959 move misplaced assert in memory leak detection stack dump code to the right location.
  libs/platform/user/ebpf_leak_detector.cpp
Labels: bug, tests

#1967 Mark all ebpf_* api's as noexcept
  include/ebpf_api.h
  libs/api/Verifier.cpp
  libs/api/ebpf_api.cpp
Labels: bug, security

#1960 Added Wix installer native project.
  .github/workflows/reusable-build.yml
  LICENSE.rtf
  docs/GettingStarted.md
  docs/InstallEbpf.md
  ebpf-for-windows.sln
  installer/Product.wxs
  installer/ebpf-for-windows.wixproj
  installer/res/eBPF logo png  150px.png
  installer/res/eBPF logo png  58px.png
  installer/res/eBPFBanner_493x58.bmp
  installer/res/eBPFDialog_493x312.bmp
  scripts/.check-license.ignore
  scripts/Setup-DevEnv.ps1
  scripts/create_package_data.bat
  scripts/run_tests.bat
  tools/elfhelper/elfhelper.sln
  tools/setup/CMakeLists.txt
  tools/setup/README.md
  tools/setup/drivers.xml
Labels: bug

#1970 Fix ossar cicd job for doc-only changes
  .github/workflows/ossar-scan.yml
Labels: bug, ci/cd

#1847 Implement sock_addr specific global helper functions
  include/bpf_helper_defs.h
  include/ebpf_structs.h
  libs/execution_context/ebpf_core.c
  libs/execution_context/ebpf_general_helpers.c
  libs/platform/ebpf_platform.h
  libs/platform/kernel/ebpf_platform_kernel.c
  libs/platform/user/ebpf_platform_user.cpp
  libs/platform/user/kernel_um.cpp
  libs/platform/user/kernel_um.h
  netebpfext/net_ebpf_ext.h
  netebpfext/net_ebpf_ext_program_info.h
  netebpfext/net_ebpf_ext_sock_addr.c
  netebpfext/net_ebpf_ext_tracelog.h
  netebpfext/sys/net_ebpf_ext_drv.c
  netebpfext/sys/netebpfext_platform.h
  netebpfext/user/fwp_um.cpp
  netebpfext/user/fwp_um.h
  scripts/execute_ebpf_cicd_tests.ps1
  scripts/run_driver_tests.psm1
  scripts/vm_run_tests.psm1
  tests/api_test/CMakeLists.txt
  tests/api_test/api_test.cpp
  tests/api_test/api_test.vcxproj
  tests/bpf2c_tests/expected/bindmonitor_dll.c
  tests/bpf2c_tests/expected/bindmonitor_raw.c
  tests/bpf2c_tests/expected/bindmonitor_sys.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_dll.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_raw.c
  tests/bpf2c_tests/expected/cgroup_sock_addr2_sys.c
  tests/connect_redirect/connect_redirect_tests.cpp
  tests/connect_redirect/connect_redirect_tests.vcxproj
  tests/end_to_end/end_to_end.cpp
  tests/libs/util/misc_helper.h
  tests/libs/util/socket_helper.cpp
  tests/netebpfext_unit/netebpfext_unit.cpp
  tests/sample/bindmonitor.c
  tests/sample/cgroup_sock_addr2.c
  tests/socket/socket_tests_common.h
Labels: enhancement

#1984 Protect ebpf_link_detach_program with a ref-count
  libs/execution_context/ebpf_link.c
Labels: bug

#1948 ebpf_program_t computes hash of program info on first attach
  libs/execution_context/ebpf_program.c
  libs/platform/ebpf_extension.c
  tests/end_to_end/end_to_end.cpp
  tests/end_to_end/helpers.h
Labels: bug
