Repository microsoft/ebpf-for-windows, pull requests merged in 2024-03, with the labels that each got.

#3163 Use custom script wrapper for all km tests to capture user, km dumps on hangs
  scripts/Run-Self-Hosted-Runner-Test.ps1
  scripts/config_test_vm.psm1
  scripts/execute_ebpf_cicd_tests.ps1
  scripts/run_driver_tests.psm1
  scripts/setup_build/setup_build.vcxproj
  scripts/setup_build/setup_build.vcxproj.filters
  scripts/vm_run_tests.psm1
Labels: enhancement, tests

#3354 Fix ring_buf issues
  libs/api/ebpf_api.cpp
  libs/runtime/ebpf_ring_buffer.c
  libs/runtime/ebpf_ring_buffer.h
  libs/shared/ebpf_ring_buffer_record.h
  tests/api_test/api_test.cpp
  tests/bpf2c_tests/expected/bindmonitor_ringbuf_dll.c
  tests/bpf2c_tests/expected/bindmonitor_ringbuf_raw.c
  tests/bpf2c_tests/expected/bindmonitor_ringbuf_sys.c
  tests/sample/bindmonitor_ringbuf.c
Labels: bug

#3353 docs: Mark C/JSON/XML code, remove stray backticks
  docs/DevelopmentGuide.md
  docs/InstallEbpf.md
  docs/NativeCodeGeneration.md
  docs/TroubleshootingGuide.md
  docs/debugging.md
  docs/eBpfExtensions.md
  docs/tutorial.md
Labels: documentation

#3349 issue priorities.
  docs/Governance.md
Labels: documentation

#3398 Fix user, kernel dump harvesting regression
  scripts/Run-Self-Hosted-Runner-Test.ps1
  scripts/cleanup_ebpf_cicd_tests.ps1
  scripts/config_test_vm.psm1
Labels: bug

#3406 Fix CVE 2024 29188
  docs/GettingStarted.md
  installer/ebpf-for-windows.wixproj
  installer/packages.config
Labels: bug, security
